### ISSUE TITLE
`string.Index` function overwrites the built-in template function `index`

### ISSUE THREAD

**Issue by telemachus** [carlmjohnson/springerle#3]
I'm very sorry to be doing this in pieces, but I just saw another case where an added function overwrites an existing function. The text/template package provides [a function named index as a way to index into arrays, slices, and maps](https://pkg.go.dev/text/template#hdr-Functions), but that name is now assigned to `string.Index`.

I want to take a little more time to check for any other such problems, but once again my instinct is to alias `string.Index` to something longer (say `stringindex`). What do you think?

Again, sorry that I didn't catch this earlier, so that it could have been one PR.

**Comment by carlmjohnson** [comment]
Sounds good. Thanks.

**Comment by carlmjohnson** [comment]
So here’s a different proposal. It’s a breaking change, but what if we just prefixed _all_ the names with packages? It’s easier to remember that every name is prefixed than that some are and some aren’t. It also fixes the issue I couldn’t fully remember before around xstring.Count, which is currently called “countpattern” due to the conflict with strings.Count.

**Comment by telemachus** [comment]
> So here’s a different proposal. It’s a breaking change, but what if we just prefixed all the names with packages? It’s easier to remember that every name is prefixed than that some are and some aren’t. It also fixes the issue I couldn’t fully remember before around xstring.Count, which is currently called “countpattern” due to the conflict with strings.Count.

Yup, that's certainly safer, though as you say, it will definitely break current templates.

I'm game, but here's my next question: what names do you think we should use as prefixes? `strings`, `filepattern`, `time`, `xstrings`, and `wordwrap` are obvious choices, but they will also cause some long function names. (They will also lead to some repetition. E.g., `wordwrapwrapstring`.) Any thoughts?

On the whole, I would vote for the simplest pattern since it's the easiest to remember:
1. Use the name of the package as the prefix.
2. Use the actual names of the functions (from their own package) as their name here.

That would give us, e.g., `wordwrapwrapstring`, but I still think that it's the least demanding thing for users. They just have to think "What name would I use if I imported this module?," drop the period, and downcase all function names.

**Comment by carlmjohnson** [comment]
That seems like the most logic way.

`wordwrapwrapstring` is the only one that’s glaringly bad, but it’s also the only function in its package, so maybe as an exception it can be just plain `wordwrap` since there’s no WrapBytes or whatever to distinguish it from.

**Comment by telemachus** [comment]
Okay, here's how `funmaps.go` looks following those rules. Three questions before I go further.
1. Now that you look at it, are you still comfortable with the long function names? (E.g., `xstringsfirstrunetoupper` is definitely not a short name!)
2. How about a compromise in the case of `wordwrap`? I aliased `wordwrap.WrapString` both to `wrapstring` and to `wordwrapwrapstring`. That way if someone is on autopilot and guesses the name based on the default pattern, they will still find the function. But other people can use the short version. Just let me know if you'd rather only one or the other.
3. If you're happy with the function names, I'll edit the `README` and the docs in `txtartmpl.go` to describe the new pattern for names, and I'll edit the `hello.txtar` example to use the new names. Can you think of anything else that needs to change?

```go
package txtartmpl

import (
	"path/filepath"
	"strings"
	"time"

	"github.com/huandu/xstrings"
	"github.com/mitchellh/go-wordwrap"
)

func xStringFuncMap() map[string]interface{} {
	return map[string]interface{}{
		"xstringscenter":           xstrings.Center,
		"xstringscount":            xstrings.Count,
		"xstringsdelete":           xstrings.Delete,
		"xstringsexpandtabs":       xstrings.ExpandTabs,
		"xstringsfirstrunetolower": xstrings.FirstRuneToLower,
		"xstringsfirstrunetoupper": xstrings.FirstRuneToUpper,
		"xstringsinsert":           xstrings.Insert,
		"xstringslastpartition": func(str, sep string) [3]string {
			f, p, l := xstrings.LastPartition(str, sep)
			return [...]string{f, p, l}
		},
		"xstringsleftjustify": xstrings.LeftJustify,
		"xstringslen":         xstrings.Len,
		"xstringspartition": func(str, sep string) [3]string {
			f, p, l := xstrings.Partition(str, sep)
			return [...]string{f, p, l}
		},
		"xstringsreverse":       xstrings.Reverse,
		"xstringsrightjustify":  xstrings.RightJustify,
		"xstringsrunewidth":     xstrings.RuneWidth,
		"xstringsscrub":         xstrings.Scrub,
		"xstringsshuffle":       xstrings.Shuffle,
		"xstringsshufflesource": xstrings.ShuffleSource,
		"xstringsslice":         xstrings.Slice,
		"xstringssqueeze":       xstrings.Squeeze,
		"xstringssuccessor":     xstrings.Successor,
		"xstringsswapcase":      xstrings.SwapCase,
		"xstringstocamelcase":   xstrings.ToCamelCase,
		"xstringstokebabcase":   xstrings.ToKebabCase,
		"xstringstosnakecase":   xstrings.ToSnakeCase,
		"xstringstranslate":     xstrings.Translate,
		"xstringswidth":         xstrings.Width,
		"xstringswordcount":     xstrings.WordCount,
		"xstringswordsplit":     xstrings.WordSplit,
	}
}

func stringFuncMap() map[string]interface{} {
	return map[string]interface{}{
		"stringscompare":        strings.Compare,
		"stringscontains":       strings.Contains,
		"stringscontainsany":    strings.ContainsAny,
		"stringscontainsrune":   strings.ContainsRune,
		"stringscount":          strings.Count,
		"stringsequalfold":      strings.EqualFold,
		"stringsfields":         strings.Fields,
		"stringsfieldsfunc":     strings.FieldsFunc,
		"stringshasprefix":      strings.HasPrefix,
		"stringshassuffix":      strings.HasSuffix,
		"stringsindex":          strings.Index,
		"stringsindexany":       strings.IndexAny,
		"stringsindexbyte":      strings.IndexByte,
		"stringsindexfunc":      strings.IndexFunc,
		"stringsindexrune":      strings.IndexRune,
		"stringsjoin":           strings.Join,
		"stringslastindex":      strings.LastIndex,
		"stringslastindexany":   strings.LastIndexAny,
		"stringslastindexbyte":  strings.LastIndexByte,
		"stringslastindexfunc":  strings.LastIndexFunc,
		"stringsmap":            strings.Map,
		"stringsrepeat":         strings.Repeat,
		"stringsreplace":        strings.Replace,
		"stringsreplaceall":     strings.ReplaceAll,
		"stringssplit":          strings.Split,
		"stringssplitafter":     strings.SplitAfter,
		"stringssplitaftern":    strings.SplitAfterN,
		"stringssplitn":         strings.SplitN,
		"stringstitle":          strings.Title,
		"stringstolower":        strings.ToLower,
		"stringstolowerspecial": strings.ToLowerSpecial,
		"stringstotitle":        strings.ToTitle,
		"stringstotitlespecial": strings.ToTitleSpecial,
		"stringstoupper":        strings.ToUpper,
		"stringstoupperspecial": strings.ToUpperSpecial,
		"stringstovalidutf8":    strings.ToValidUTF8,
		"stringstrim":           strings.Trim,
		"stringstrimfunc":       strings.TrimFunc,
		"stringstrimleft":       strings.TrimLeft,
		"stringstrimleftfunc":   strings.TrimLeftFunc,
		"stringstrimprefix":     strings.TrimPrefix,
		"stringstrimright":      strings.TrimRight,
		"stringstrimrightfunc":  strings.TrimRightFunc,
		"stringstrimspace":      strings.TrimSpace,
		"stringstrimsuffix":     strings.TrimSuffix,
	}
}

func filepathFuncMap() map[string]interface{} {
	return map[string]interface{}{
		"filepathabs":       filepath.Abs,
		"filepathbase":      filepath.Base,
		"filepathclean":     filepath.Clean,
		"filepathdir":       filepath.Dir,
		"filepathext":       filepath.Ext,
		"filepathjoin":      filepath.Join,
		"filepathfromslash": filepath.FromSlash,
		"filepathisabs":     filepath.IsAbs,
		"filepathmatch":     filepath.Match,
		"filepathrel":       filepath.Rel,
		"filepathsplit": func(path string) [2]string {
			head, tail := filepath.Split(path)
			return [...]string{head, tail}
		},
		"filepathsplitlist":  filepath.SplitList,
		"filepathtoslash":    filepath.ToSlash,
		"filepathvolumename": filepath.VolumeName,
	}
}

func timeFuncMap() map[string]interface{} {
	return map[string]interface{}{
		"timedate":          time.Date,
		"timenow":           time.Now,
		"timeparse":         time.Parse,
		"timeparseduration": time.ParseDuration,
	}
}

func wordWrapFuncMap() map[string]interface{} {
	return map[string]interface{}{
		"wordwrapwrapstring": wordwrap.WrapString,
		"wrapstring":         wordwrap.WrapString,
	}
}
```

**Comment by carlmjohnson** [comment]
I can’t think of anything else that needs to change. That seems good.

**Comment by telemachus** [comment]
Should be fixed by https://github.com/carlmjohnson/springerle/commit/adcf0cdb4a8c238cee0850e66860e1a4390b5c00
